### DISCUSSION TITLE
Server Generation

### DISCUSSION THREAD

**Discussion by dmarginian** [quarkiverse/quarkus-openapi-generator#1040] [General]
Hi, does this server generation work? 

https://docs.quarkiverse.io/quarkus-openapi-generator/dev/server.html

Contrary to this page, published artifacts exist, I am trying to use 2.8.2-lts (I have tried a few other versions too). 

My setup:

```
    <dependency>
      <groupId>io.quarkiverse.openapi.generator</groupId>
      <artifactId>quarkus-openapi-generator-server</artifactId>
      <version>2.8.2-lts</version>
    </dependency>
 ```
    
In my application.yml, I have tried several variations of the config (guide says it should be quarkus.openapi.generator.spec):

```
quarkus:
  ...
   openapi:
    generator:
      spec: openapi.yaml
      input-base-dir: target/openapi/combined
      base-package: com.myPackage
      additional-api-type-annotations: "@com.myPackage.Secured"
      type-mappings:
        Double: java.math.BigDecimal
```

The above config seems to partially work.  But, I have the input-base-dir set as target/openapi/combined (exists) but something is appending src/main/resources ...

[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.19.2:generate-code (default) on project mp-backend: Quarkus code generation phase has failed: InvocationTargetException: The OpenAPI input base directory does not exist. Please create the directory at /Users/davidmarginian/projects/Marketplace-Backend/target/openapi/combined/src/main/resources -> [Help 1]

If I switch my dependency to:

```
 <groupId>io.quarkiverse.openapi.generator</groupId>
 <artifactId>quarkus-openapi-generator</artifactId>
 ```
      
 and build (the client), everything works fine with the following config (per the client guide):

```
  openapi-generator:
    codegen:
      base-package: com.mypackage.generated
      input-base-dir: target/openapi/combined
      additional-api-type-annotations: "@com.myPackage.Secured"
      type-mappings:
        Double: java.math.BigDecimal
```

I am not sure if the documentation/guide is out of date or if this isn't supposed to work yet.  I am happy to update the guide if this is supposed to work.

**Comment by ricardozanini** [comment]
@carlesarnal can you pleae take a look?

**Comment by dmarginian** [comment]
I was able to get this to work with a very basic set-up, but it doesn't seem to meet my needs.  I have some external refs like 

`$ref: '../schemas/additional-schemas.yaml#/OptionSetMap'`

that this plugin seems unable to resolve.  

I am getting the following errors when I try: 

Server Stack Trace:
java.lang.IllegalArgumentException: URI is not absolute
	at java.base/java.net.URL.of(URL.java:862)
	at java.base/java.net.URI.toURL(URI.java:1172)

These get written out to target/classes/generated-sources/jaxrs/PROJECT_GENERATION_FAILED.txt

To workaround this I was trying to pre-process my spec via: 

```
<plugin>
        <groupId>io.swagger.codegen.v3</groupId>
        <artifactId>swagger-codegen-maven-plugin</artifactId>
        <version>3.0.63</version>
        <executions>
          <execution>
            <id>bundle-openapi</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>${project.basedir}/src/main/resources/openapi/openapi.yaml</inputSpec>
              <output>${project.basedir}/target/openapi</output>
              <language>openapi-yaml</language>
              <generateSupportingFiles>false</generateSupportingFiles>
              <configOptions>
                <outputFile>final.yaml</outputFile>
              </configOptions>
            </configuration>
          </execution>
        </executions>
      </plugin>
 ```

This works, and properly resolves the refs but when I try to update my config to use the outputted file:

```
  openapi:
    generator:
      spec: final.yaml
      input-base-dir: target/openapi
      base-package: com.bluestaq.marketplace.api.generated
      reactive: false
```

I get the following:
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.19.2:generate-code (default) on project mp-backend: Quarkus code generation phase has failed: InvocationTargetException: The OpenAPI input base directory does not exist. Please create the directory at /projects/test-project/target/openapi/src/main/resources
