### ISSUE TITLE
No way to avoid name clash due to case of property names in the model's generated getter and setter

### ISSUE THREAD

**Issue by adumeige** [quarkiverse/quarkus-openapi-generator#1001]
Considering the following openApi schema sample :
```yaml
myObject:
  type: object
  properties:
    a:
      type: integer
      format: int64
      description: Some random property
      example: 1
    A:
      type: integer
      type: int64
      description: Another
      example: 42
```

The generated model will be (skipping annotations and docs for brevity), which is obviously invalid:
```java

public class MyObject  {

    private Long a;
    private Long A;

    public Boolean getA() {
        return a;
    }

    public Boolean getA() {
        return A;
    }

  // Similar issue with setters.
}
```

Unless I'm mistaken, I can't find a way around this without resorting to custom template. Could it be possible to provide a config option to maintain properties case, or any other way to specify more deeply what is generated in models (I'd be fine with public final fields and no accessors as a response shouldn't be mutated anyway) ?
