### ISSUE TITLE
Yaml configuration not honored.

### ISSUE THREAD

**Issue by mike-hampton-float** [quarkiverse/quarkus-openapi-generator#131]
My configuration is in a yaml file.

My openapi file is here crm-svc/service/src/main/openapi/sellerdeal.yaml

My application.yaml file has

```
quarkus:
  openapi-generator:
    codegen:
      spec:
        sellerdeal_yaml:
          base-package:
            com.floatfin.sellerdeal.openapi
```

## Expected
The generated interfaces have the package:

```
com.floatfin.sellerdeal.openapi;
```

## Actual
The generated interfaces have the package:

```
package org.openapi.quarkus.sellerdeal_yaml.api;
```
