### ISSUE TITLE
Wrong class generated for enum

### ISSUE THREAD

**Issue by lburgazzoli** [quarkiverse/quarkus-openapi-generator#28]
Ginevn the follwogin OpenApi scheme:

```yaml
   ConnectorNamespaceState:
      type: string
      enum:
        - disconnected
        - ready
        - deleting
```

the extension generates an invalid class:

```java
@JsonIgnoreProperties(ignoreUnknown = true)
public enum ConnectorNamespaceState {
    private String value;

    ConnectorNamespaceState(String value){
        this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static ConnectorNamespaceState fromValue(String text) {
        for (ConnectorNamespaceState b : ConnectorNamespaceState.values()) {
            if (String.valueOf(b.value).equals(text)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }
}
````

Which is wrong as it does not include the listed enum values.

As an additional note, `ConnectorNamespaceState.values()` should probably be cached as each call to `values()` creates a copy of the enum values for each invocation
