### ISSUE TITLE
Config-Request: customize configKey name

### ISSUE THREAD

**Issue by lostiniceland** [quarkiverse/quarkus-openapi-generator#363]
Currently the `configKey` is extracted from the `openApiSpecId` (which in case of `myfile.yaml` is `myfile_yaml`).
https://github.com/quarkiverse/quarkus-openapi-generator/blob/aac4adf289f9aef364ae25c759d1cf0351c402fa/deployment/src/main/resources/templates/api.qute#L37

We would like to migrate from openapitools-maven-plugin to the quarkiverse-plugin and have lots of configKeys configured. It would be nice if we could keep those keys in our current configuration and just adjust the generator to use this one.

**Comment by hbelmiro** [comment]
@lostiniceland I'm not sure I understand.
In order to know which `configKey` to use we would have to map `myfile.yaml` to `my_custom_config_key` in configurations.
Is that right?

**Comment by hbelmiro** [comment]
Sounds reasonable to me.
@ricardozanini WDYT?

**Comment by ricardozanini** [comment]
Go ahead! Sounds simple enough.

**Comment by hbelmiro** [comment]
@lostiniceland I don't have the time to implement it right now, but I added it to our backlog.
If you want to send a PR, I'll be happy to help with the review.

**Comment by mcruzdev** [comment]
Hi @hbelmiro, how are you? 

Can you assign it for me? ty!

**Comment by mcruzdev** [comment]
Hi @hbelmiro, what do you think about this proposal:

If the user set a property:

```properties
quarkus.openapi-generator.codegen.spec.swapi_yaml.config-key=swapi
```

Then the `@RegisterRestClient` annotation will be:

```java
@RegisterRestClient(baseUri="https://swapi.dev", configKey="swapi")
```

If not, we will follow the current behavior, it makes sense?


```java
@RegisterRestClient(baseUri="https://swapi.dev", configKey="swapi_yaml")
```

**Comment by hbelmiro** [comment]
@mcruzdev Not really because the configKey is the key that the extension uses to find a property. 

For instance, in quarkus.openapi-generator.codegen.spec.swapi_yaml.config-key, swapi_yaml is the config key.

I think the approach would be having a property that accepts a Map as value. 
That Map would have the openapi file name as its key and the custom config key as its value. 

For example:
custom-config-keys.swapi_yaml=xpto

Then the extension would use

quarkus.openapi-generator.codegen.spec.xpto.any-config

I hope it's clear enough. I'm typing on my phone.

**Comment by mcruzdev** [comment]
@hbelmiro thank you for your explanation. 

Reading the [rest-client](https://quarkus.io/guides/rest-client#create-the-configuration) documentation the goal of the `configKey` in `@RegisterRestClient` is to make it easy its configuration. Here is the new proposal:

```yaml
quarkus:
  openapi-generator:
    codegen:
      spec:
        swapi_yaml:
          config-key: xpto
    config-keys:
      xpto:
        url: http://local
        scope: jakarta.enterprise.context.ApplicationScoped # I do not know if it is a valid scope value 
        # because in the rest-client docs, I saw: jakarta.inject.* classes.
```

And the generated annotation will be:

```java
@ApplicationScoped
@RegisterRestClient(baseUri="http://local", configKey="swapi")

```

I have a doubt yet... it is really necessary to create this map? Because the `rest-client` already looks for `quarkus.rest-client.<config-key>.url=https://stage.code.quarkus.io/api`
