### ISSUE TITLE
Handling of deprectated fields

### ISSUE THREAD

**Issue by lburgazzoli** [quarkiverse/quarkus-openapi-generator#38]
If a schema contains a deprecated field, the generated class may be invalid, as example given the schema below: 

```yaml
    MetaV1Condition:
      type: object
      properties:
        type:
          type: string
        reason:
          type: string
        message:
          type: string
        status:
          type: string
        lastTransitionTime:
          type: string
          deprecated: true
        last_transition_time:
          type: string
          #format: date-time
```

The generated class is:

```java
@JsonIgnoreProperties(ignoreUnknown = true)
public class MetaV1Condition  {

    private String type;
    private String reason;
    private String message;
    private String status;
    private String lastTransitionTime;
    private String lastTransitionTime;
}
 ```
 
As you can notice, `lastTransitionTime` get duplicated which result in a complication error. 
 
It would be nice to have an option to control the behavior of the generator i.e. to skip any deprecated fields.
