### ISSUE TITLE
Default values for custom pojo

### ISSUE THREAD

**Issue by michapojo** [quarkiverse/quarkus-openapi-generator#713]
Hello,

we are using this lib to generate our REST API and we are trying to define default values for a custom pojo. But this results in invalid java code.
Example:
```
type: object
title: customDto
properties:
  enabled:
    type: boolean
    default: false
  url:
    type: string
    default: ""
required:
  - enabled
  - url
default:
  enabled: false
  url: ""
```
  
  
```
public class AddCustomDtoRequest  {
...    
    private CustomDto customDto = {enabled=false, url=};
...
```
The pojo itself looks fine
```
public class CustomDto {

    @NotNull
    private Boolean enabled = false;
    @NotNull
    private String url = "";
```

Do I miss sth here or is this topic just not covered yet?
Thanks for your support in advance.
