### ISSUE TITLE
number enums generate non-compiling code

### ISSUE THREAD

**Issue by Shohou** [quarkiverse/quarkus-openapi-generator#715]
Got to `integration-tests/enum-property/src/main/openapi/enum-property.yaml`. Change type for enum from `string` to `number` and enum values from `'text'` to `1`:
```
components:
  schemas:
    Echo:
      type: object
      properties:
        echoedMsgType:
          type: string
    Message:
      type: object
      required:
        - msgType
      properties:
        msgType:
          type: number    <---
          enum:
            - 1          <---
```
Compile it and check generated `org.openapi.quarkus.enum_property_yaml.model.Message` class. It will contain enum value - 
```
@JsonIgnoreProperties(ignoreUnknown = true)
public class Message  {


    public enum MsgTypeEnum {
        NUMBER_1(BigDecimal.valueOf(new BigDecimal("1")));    // THIS IS NOT COMPILING

        // caching enum access
        private static final java.util.EnumSet<MsgTypeEnum> values = java.util.EnumSet.allOf(MsgTypeEnum.class);

        BigDecimal value;
```
`BigDecimal.valueOf(new BigDecimal("1"))` this part can not compile
