### ISSUE TITLE
Bean validation not working

### ISSUE THREAD

**Issue by krisraich** [quarkiverse/quarkus-openapi-generator#851]
Hello

It seems that server side bean validation is ignored. 
YML Schema:
```
    UserCredentials:
      type: object
      required:
        - userName
        - password
      properties:
        userName:
          type: string
        password:
          type: string
``` 

Beans
```
    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("userName")
    private String userName;
    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("password")
    private String password;
```

A request that is missing a parameter should yield HTTP Code 400 

Is there a configuration or package that I have overlooked?
