### ISSUE TITLE
Missing annotations @NotNull @Patters, @Size ... to all PathParams, HeaderParams

### ISSUE THREAD

**Issue by JPSantistebanQ** [quarkiverse/quarkus-openapi-generator#976]
In client side, using versión 2.8.0:

The jakarta validation contrain anotations not added on the HeaderParams and PathParams:

Example:

`OpenApi.yml`

```yaml
...
  parameters:
    - name: Ocp-Apim-Subscription-Key
          in: header
          description: 'Identificador de suscripción, este campo es obtenido al momento de la suscripción.'
          required: true
          schema:
            maxLength: 32
            minLength: 32
            pattern: '^[a-z0-9]{32}$'
            type: string
            example: 3cfdad6e03c24d0ab7112dce75cdba35
        - name: currentAccountId
          in: path
          description: ID de la cuenta
          required: true
          schema:
            type: string
            maxLength: 14
            minLength: 14
            pattern: '^[0-9]{14}$'
            example: '19318085994179'

```

`Interface class generated`:

```java
@Path("my-path")
public inteface MyRest {

public Response myEndpoint (
@jakarta.validation.Valid @io.quarkiverse.openapi.generator.annotations.GeneratedParam("Ocp-Apim-Subscription-Key") @jakarta.ws.rs.HeaderParam("Ocp-Apim-Subscription-Key")String ocpApimSubscriptionKey, 
        @jakarta.validation.Valid @io.quarkiverse.openapi.generator.annotations.GeneratedParam("currentAccountId") @jakarta.ws.rs.PathParam("currentAccountId")String currentAccountId,
)
}
```
